SCREEN 0
WIDTH 80, 25
CLS

PRINT "Press any key to start!"

SLEEP

LPRINT "  Ersoy's PC Lab Printer Test Program for QBasic"
LPRINT "--------------------------------------------------"
LPRINT "12345678901234567890123456789012345678901234567890"
LPRINT "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
LPRINT "abcdefghijklmnopqrstuvwxyz"
LPRINT "--------------------------------------------------"
LPRINT CHR$(12)

PRINT "Test data has been sended to the printer!"

END
